# Generated by Django 3.1.2 on 2021-10-10 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create timestamp')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update timestamp')),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Address')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is SuperUser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('delete_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='delete time')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_of', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='StartUp',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create timestamp')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update timestamp')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('delete_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='delete time')),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('website', models.URLField(null=True, verbose_name='website')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header_of', to='account.profile', verbose_name='header')),
            ],
            options={
                'verbose_name': 'startUp',
                'verbose_name_plural': 'startUps',
            },
        ),
        migrations.CreateModel(
            name='StartUpMembers',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create timestamp')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update timestamp')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('delete_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='delete time')),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('job_title', models.CharField(db_index=True, max_length=120, verbose_name='job title')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', related_query_name='members', to='account.profile', verbose_name='member')),
                ('startUp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', related_query_name='members', to='account.startup', verbose_name='startUp')),
            ],
            options={
                'verbose_name': 'startup member',
                'verbose_name_plural': 'startup members',
            },
        ),
    ]
