# Generated by Django 3.1.2 on 2021-10-05 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create timestamp')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update timestamp')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('delete_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='delete time')),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('street', models.CharField(max_length=120, verbose_name='Street')),
                ('post_code', models.CharField(max_length=10, verbose_name='Post Code')),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create timestamp')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update timestamp')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('delete_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='delete time')),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('capacity', models.PositiveSmallIntegerField(default=1, verbose_name='capacity')),
                ('price_per_hour', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Price per Hours')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', related_query_name='tables', to='building.building', verbose_name='building')),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'tables',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create timestamp')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update timestamp')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('delete_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='delete time')),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('capacity', models.PositiveSmallIntegerField(default=6, verbose_name='capacity')),
                ('has_tv', models.BooleanField(default=False, verbose_name='has TV')),
                ('has_printer', models.BooleanField(default=False, verbose_name='has TV')),
                ('price_per_day', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='price per day')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', related_query_name='rooms', to='building.building', verbose_name='building')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
    ]
