# Generated by Django 3.1.2 on 2021-10-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create timestamp')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update timestamp')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('delete_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='delete time')),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('start_at', models.DateTimeField(auto_now=True, verbose_name='start_at')),
                ('end_at', models.DateTimeField(verbose_name='end_at')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', related_query_name='books', to='building.table', verbose_name='table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', related_query_name='books', to='account.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'book table',
                'verbose_name_plural': 'book tables',
            },
        ),
        migrations.CreateModel(
            name='BookRoom',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create timestamp')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update timestamp')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('delete_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='delete time')),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('start_at', models.DateTimeField(auto_now=True, verbose_name='start at')),
                ('end_at', models.DateTimeField(verbose_name='end ar')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', related_query_name='books', to='building.room', verbose_name='room')),
                ('startUp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', related_query_name='books', to='account.startup', verbose_name='startUp')),
            ],
            options={
                'verbose_name': 'book room',
                'verbose_name_plural': 'book rooms',
            },
        ),
    ]
